### PR TITLE
prematureOptimization

### PR DESCRIPTION
**Pull request by Aprillion**

### CODE REVIEW

**Comment by Aprillion** [comment]
First time creating PR from codesandbox - no idea how to turn off the default prettier config that updated the original files yet...

Do you have a `.prettierrc` that I can include in my fork to revert the changes to your preferred config?

**Comment by Aprillion** [comment]
ah, backlink to the codesandbox: https://codesandbox.io/s/serene-andras-29uh8?file=/src/exercise/prematureOptimization.js

**Review by kentcdodds — APPROVED** [review]
Super duper! Thank you 👏

**Comment by kentcdodds** [comment]
@all-contributors please add @Aprillion for code

**Pull request merged**
